package chap08;

public class A07_ExceptionEx7 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
   System.out.println(1);
   System.out.println(2);
   try {
	   System.out.println(3);
       System.out.println(0/0);
       System.out.println(4); //실행되지 않는다.
   }catch(ArithmeticException ae) {
	   if(ae instanceof ArithmeticException)
		   System.out.println("true");
	   System.out.println("ArithmeticException");
   } catch(Exception e) {
	   System.out.println("Exception");
   } //try-catch의 끝
   System.out.println(6);
	}//main 메서드의 끝
	/*
1
2
3
true
ArithmeticException
6
	 */
}
